-- schema inicial do engagement-service no postgres (quinta entrega).
--
-- gerado a partir do mapeamento jpa das entidades (schema-generation do hibernate
-- contra um postgres 16) e revisado a mao. e um banco separado do do monolito, com
-- usuario proprio: nenhuma chave estrangeira aponta para posts, que vive em outro
-- servico. post_id e so um numero, como desde a segunda entrega.
--
-- inclui a auditoria do comentario (envers), a restricao de unicidade das reacoes
-- (terceira entrega) e o submission_id do comentario que chega pela fila (quarta).

    create sequence revinfo_seq start with 1 increment by 50;

    create table comments (
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        post_id bigint not null,
        version bigint,
        submission_id varchar(36),
        author_name varchar(255) not null,
        content text not null,
        primary key (id),
        constraint uk_comments_submission_id unique (submission_id)
    );

    create table comments_aud (
        rev integer not null,
        revtype smallint,
        created_at timestamp(6) with time zone,
        id bigint not null,
        post_id bigint,
        submission_id varchar(36),
        author_name varchar(255),
        content text,
        primary key (rev, id)
    );

    create table reactions (
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        post_id bigint not null,
        version bigint,
        type varchar(20) not null check (type in ('CORACAO','CAFE','IDEIA')),
        reader_name varchar(255) not null,
        primary key (id),
        constraint uk_reactions_post_reader_type unique (post_id, reader_name, type)
    );

    create table revinfo (
        rev integer not null,
        revtstmp bigint,
        primary key (rev)
    );

    create index idx_comments_post_id 
       on comments (post_id);

    create index idx_reactions_post_id 
       on reactions (post_id);

    alter table if exists comments_aud 
       add constraint FKprr41p1i93lyk0qha4ab9lfdb 
       foreign key (rev) 
       references revinfo;
