-- schema inicial do blog-api no postgres (quinta entrega).
--
-- gerado a partir do mapeamento jpa das entidades (schema-generation do hibernate
-- contra um postgres 16) e revisado a mao, em vez de escrito do zero: assim o
-- ddl-auto=validate do perfil container confere exatamente o que as entidades esperam.
-- daqui para frente, mudanca de schema e um V2, V3..., nunca uma edicao deste arquivo:
-- o flyway guarda o checksum de cada migracao aplicada e recusa a que mudou.
--
-- o conteudo reflete as quatro entregas: autores e posts com travamento otimista
-- (version) e indices alinhados as consultas (segunda), as tabelas de auditoria do
-- envers (segunda), o outbox e a copia local dos contadores (quarta).

    create sequence revinfo_seq start with 1 increment by 50;

    create table authors (
        id bigint generated by default as identity,
        version bigint,
        bio varchar(500),
        email varchar(255) not null unique,
        name varchar(255) not null,
        primary key (id)
    );

    create table authors_aud (
        rev integer not null,
        revtype smallint,
        id bigint not null,
        bio varchar(500),
        email varchar(255),
        name varchar(255),
        primary key (rev, id)
    );

    create table engagement_counters (
        comments bigint not null,
        post_id bigint not null,
        reactions bigint not null,
        updated_at timestamp(6) with time zone not null,
        version bigint,
        last_change varchar(40),
        primary key (post_id)
    );

    create table outbox_messages (
        attempts integer not null,
        created_at timestamp(6) with time zone not null,
        published_at timestamp(6) with time zone,
        id varchar(36) not null,
        last_error varchar(500),
        trace_parent varchar(55),
        exchange varchar(255) not null,
        payload text not null,
        routing_key varchar(255) not null,
        type varchar(255) not null,
        primary key (id)
    );

    create table posts (
        author_id bigint not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        published_at timestamp(6) with time zone,
        version bigint,
        content text not null,
        status varchar(255) not null check (status in ('DRAFT','PUBLISHED')),
        title varchar(255) not null,
        primary key (id)
    );

    create table posts_aud (
        rev integer not null,
        revtype smallint,
        author_id bigint,
        created_at timestamp(6) with time zone,
        id bigint not null,
        published_at timestamp(6) with time zone,
        content text,
        status varchar(255) check (status in ('DRAFT','PUBLISHED')),
        title varchar(255),
        primary key (rev, id)
    );

    create table revinfo (
        rev integer not null,
        revtstmp bigint,
        primary key (rev)
    );

    create index idx_outbox_pending 
       on outbox_messages (published_at, created_at);

    create index idx_posts_author_id 
       on posts (author_id);

    create index idx_posts_status 
       on posts (status);

    create index idx_posts_created_at 
       on posts (created_at);

    alter table if exists authors_aud 
       add constraint FKq0j6ylpjvyj8b28yj2v7d6vhj 
       foreign key (rev) 
       references revinfo;

    alter table if exists posts_aud 
       add constraint FKgd2crtj4u69d0y8bba9jwogbi 
       foreign key (rev) 
       references revinfo;
